excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://pacelat.github.io
title: Some Thoughts
tagline: I keep meaning to write these things down!
description: My awesome new site
paginate: 5
