excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://pacelat.github.io
title: Some Thoughts
tagline: (that I've been meaning to write down)
description: My awesome new site
paginate: 5
